# Dockerfile.dev

FROM node:23-alpine

WORKDIR /app

# Salin package.json dan install dependency
COPY package*.json ./
RUN npm install

# Salin seluruh source code
COPY . .

# Generate Prisma Client
RUN npx prisma generate

# Expose port 3000
EXPOSE 3000

# Jalankan dalam development mode
CMD ["npm", "run", "dev"]
